version: "3.8"

services:
  app:
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pwa.rule=Host(`pwa.erikna.com`)"
      - "traefik.http.routers.pwa.entrypoints=web, websecure"
      - "traefik.http.routers.pwa.tls=true"
      - "traefik.http.routers.pwa.tls.certresolver=production"
    volumes:
      - ./mobile/index.html:/usr/share/nginx/html/index.html
      - ./mobile/scripts.js:/usr/share/nginx/html/scripts.js
      - ./mobile/service-worker.js:/usr/share/nginx/html/service-worker.js
      - ./nginx.conf:/etc/nginx/nginx.conf
